"use client";
import {useEffect,useMemo,useState} from "react";
type Payment={id:string;amount:number;date:string};type Bill={id:string;vendor:string;amount:number;date:string;payments:Payment[]};
const money=(n:number)=>`Rs. ${Math.round(n).toLocaleString()}`;const today=()=>new Date().toISOString().slice(0,10);
export default function Page(){
 const [bills,setBills]=useState<Bill[]>([]),[ready,setReady]=useState(false),[add,setAdd]=useState(false),[vendor,setVendor]=useState(""),[amount,setAmount]=useState(""),[initialPaid,setInitialPaid]=useState("0"),[date,setDate]=useState(today()),[q,setQ]=useState("");
 useEffect(()=>{try{setBills(JSON.parse(localStorage.getItem("lb-payables")||"[]"))}catch{}setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem("lb-payables",JSON.stringify(bills))},[bills,ready]);
 const paid=(b:Bill)=>b.payments.reduce((s,p)=>s+p.amount,0),pending=(b:Bill)=>Math.max(0,b.amount-paid(b));
 const names=useMemo(()=>Array.from(new Set(bills.map(b=>b.vendor))),[bills]);
 const vendorRows=useMemo(()=>names.filter(v=>v.toLowerCase().includes(q.toLowerCase())).map(v=>{const bs=bills.filter(b=>b.vendor===v),total=bs.reduce((s,b)=>s+b.amount,0),p=bs.reduce((s,b)=>s+paid(b),0),lastBill=[...bs].sort((a,b)=>b.date.localeCompare(a.date))[0]?.date||"—",lastPay=bs.flatMap(b=>b.payments).sort((a,b)=>b.date.localeCompare(a.date))[0]?.date||"—";return{v,bs,total,p,due:Math.max(0,total-p),lastBill,lastPay}}).sort((a,b)=>b.due-a.due),[bills,names,q]);
 const total=bills.reduce((s,b)=>s+b.amount,0),tp=bills.reduce((s,b)=>s+paid(b),0),due=total-tp;
 function save(e:React.FormEvent){e.preventDefault();const a=Number(amount),p=Math.min(Number(initialPaid)||0,a);if(!vendor.trim()||a<=0)return;setBills(x=>[{id:crypto.randomUUID(),vendor:vendor.trim(),amount:a,date,payments:p?[{id:crypto.randomUUID(),amount:p,date}]:[]},...x]);setVendor("");setAmount("");setInitialPaid("0");setDate(today());setAdd(false)}
 function addBillTo(v:string){const raw=prompt(`New bill amount for ${v}`);if(!raw)return;const n=Number(raw);if(!n||n<=0)return;const d=prompt("Bill date (YYYY-MM-DD)",today())||today();setBills(x=>[{id:crypto.randomUUID(),vendor:v,amount:n,date:d,payments:[]},...x])}
 function payVendor(v:string){const vr=vendorRows.find(x=>x.v===v);if(!vr||vr.due<=0)return;const raw=prompt(`Payment to ${v} — Total pending ${money(vr.due)}`);if(!raw)return;let n=Math.min(Number(raw),vr.due);if(!n||n<=0)return;const d=prompt("Payment date (YYYY-MM-DD)",today())||today();setBills(x=>{const copy=x.map(b=>({...b,payments:[...b.payments]}));for(const b of copy.filter(b=>b.vendor===v).sort((a,b)=>a.date.localeCompare(b.date))){if(n<=0)break;const rem=Math.max(0,b.amount-b.payments.reduce((s,p)=>s+p.amount,0));const use=Math.min(rem,n);if(use>0){b.payments.push({id:crypto.randomUUID(),amount:use,date:d});n-=use}}return copy})}
 function editLastBill(v:string){const bs=bills.filter(b=>b.vendor===v).sort((a,b)=>b.date.localeCompare(a.date));const b=bs[0];if(!b)return;const raw=prompt(`Edit latest bill for ${v}`,String(b.amount));if(!raw)return;const n=Number(raw);if(!n||n<paid(b))return alert(`Bill cannot be below already paid ${money(paid(b))}`);setBills(x=>x.map(y=>y.id===b.id?{...y,amount:n}:y))}
 return <main className="min-h-screen bg-[#f4f5f7] text-slate-900 pb-16"><header className="bg-white border-b sticky top-0 z-20"><div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between"><div className="flex items-center gap-3"><img src="/brand/london-bite-logo.png" className="w-11 h-11 object-contain" alt="London Bite"/><div><h1 className="font-black leading-tight">London Bite Payables</h1><p className="text-xs text-slate-500">Running Supplier Khata</p></div></div><button onClick={()=>setAdd(!add)} className="bg-[#172554] text-white rounded-xl px-4 py-2.5 font-bold">+ New Supplier Bill</button></div></header><section className="max-w-6xl mx-auto p-4">
 <div className="grid grid-cols-2 md:grid-cols-5 gap-2 mb-4"><Card l="Total Bills" v={money(total)}/><Card l="Total Paid" v={money(tp)}/><Card l="Dena Baqi" v={money(due)}/><Card l="Payable Suppliers" v={String(vendorRows.filter(x=>x.due>0).length)}/><Card l="Cleared Suppliers" v={String(vendorRows.filter(x=>x.due===0).length)}/></div>
 {add&&<form onSubmit={save} className="bg-white border rounded-2xl p-4 mb-4"><h2 className="font-black text-lg mb-3">New Supplier / Bill</h2><div className="grid md:grid-cols-5 gap-3"><Field label="Supplier Name"><input list="suppliers" className="field" value={vendor} onChange={e=>setVendor(e.target.value)} required/><datalist id="suppliers">{names.map(n=><option key={n} value={n}/>)}</datalist></Field><Field label="Bill Amount"><input className="field" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} required/></Field><Field label="Paid Amount"><input className="field" inputMode="numeric" value={initialPaid} onChange={e=>setInitialPaid(e.target.value)}/></Field><Field label="Pending"><input className="field" value={money(Math.max(0,(Number(amount)||0)-(Number(initialPaid)||0)))} readOnly/></Field><Field label="Date"><input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)} required/></Field></div><button className="mt-4 bg-[#172554] text-white rounded-xl px-6 py-3 font-bold">Save</button></form>}
 <input className="field mb-3 max-w-sm" placeholder="Search supplier..." value={q} onChange={e=>setQ(e.target.value)}/><div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full min-w-[1000px] text-sm"><thead className="bg-[#172554] text-white"><tr><Th>Supplier</Th><Th>Last Bill</Th><Th>Total Bills</Th><Th>Paid</Th><Th>Pending</Th><Th>Last Payment</Th><Th>Status</Th><Th>Actions</Th></tr></thead><tbody>{vendorRows.map(r=><tr key={r.v} className="border-b"><Td bold>{r.v}</Td><Td>{r.lastBill}</Td><Td>{money(r.total)}</Td><Td>{money(r.p)}</Td><Td bold>{money(r.due)}</Td><Td>{r.lastPay}</Td><Td><span className={`px-2 py-1 rounded-full text-xs font-bold ${r.due===0?"bg-green-100 text-green-700":"bg-amber-100 text-amber-700"}`}>{r.due===0?"CLEARED":"PAYABLE"}</span></Td><Td><div className="flex gap-2"><button onClick={()=>addBillTo(r.v)} className="btn">+ Bill</button>{r.due>0&&<button onClick={()=>payVendor(r.v)} className="btn">+ Payment</button>}<button onClick={()=>editLastBill(r.v)} className="btn">Edit</button></div></Td></tr>)}{!vendorRows.length&&<tr><td colSpan={8} className="text-center text-slate-400 py-12">No supplier added yet.</td></tr>}</tbody></table></div></section><style jsx global>{`.field{width:100%;border:1px solid #d1d5db;border-radius:10px;padding:11px 12px;background:white;outline:none}.field:focus{border-color:#172554}.btn{border:1px solid #172554;color:#172554;border-radius:8px;padding:7px 10px;font-weight:700;white-space:nowrap}`}</style></main>}
function Card({l,v}:{l:string,v:string}){return <div className="bg-white border rounded-xl p-3"><div className="text-[11px] text-slate-500">{l}</div><div className="font-black text-lg">{v}</div></div>};function Field({label,children}:{label:string,children:React.ReactNode}){return <label><span className="block text-xs font-bold mb-1">{label}</span>{children}</label>};function Th({children}:{children:React.ReactNode}){return <th className="text-left px-4 py-3 whitespace-nowrap">{children}</th>};function Td({children,bold=false}:{children:React.ReactNode,bold?:boolean}){return <td className={`px-4 py-3 whitespace-nowrap ${bold?"font-bold":""}`}>{children}</td>}
