"use client";
import {useEffect,useMemo,useState} from "react";
type Payment={id:string;amount:number;date:string}; type Bill={id:string;vendor:string;amount:number;date:string;payments:Payment[]};
const money=(n:number)=>`Rs. ${Math.round(n).toLocaleString()}`; const today=()=>new Date().toISOString().slice(0,10);
export default function Page(){
 const [bills,setBills]=useState<Bill[]>([]),[ready,setReady]=useState(false),[add,setAdd]=useState(false),[vendor,setVendor]=useState(""),[amount,setAmount]=useState(""),[initialPaid,setInitialPaid]=useState("0"),[date,setDate]=useState(today()),[q,setQ]=useState("");
 useEffect(()=>{try{setBills(JSON.parse(localStorage.getItem("lb-payables")||"[]"))}catch{}setReady(true)},[]); useEffect(()=>{if(ready)localStorage.setItem("lb-payables",JSON.stringify(bills))},[bills,ready]);
 const paid=(b:Bill)=>b.payments.reduce((s,p)=>s+p.amount,0), pending=(b:Bill)=>Math.max(0,b.amount-paid(b));
 const rows=useMemo(()=>bills.filter(b=>b.vendor.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>pending(b)-pending(a)),[bills,q]);
 const total=bills.reduce((s,b)=>s+b.amount,0),tp=bills.reduce((s,b)=>s+paid(b),0),due=total-tp, payable=bills.filter(b=>pending(b)>0).length, cleared=bills.filter(b=>pending(b)===0).length;
 function save(e:React.FormEvent){e.preventDefault();const a=Number(amount),p=Math.min(Number(initialPaid)||0,a);if(!vendor.trim()||a<=0)return;setBills(x=>[{id:crypto.randomUUID(),vendor:vendor.trim(),amount:a,date,payments:p?[{id:crypto.randomUUID(),amount:p,date}]:[]},...x]);setVendor("");setAmount("");setInitialPaid("0");setDate(today());setAdd(false)}
 function makePayment(id:string){const b=bills.find(x=>x.id===id);if(!b)return;const raw=prompt(`Payment amount — Pending ${money(pending(b))}`);if(!raw)return;const n=Math.min(Number(raw),pending(b));if(!n||n<=0)return;const d=prompt("Payment date (YYYY-MM-DD)",today())||today();setBills(x=>x.map(y=>y.id===id?{...y,payments:[...y.payments,{id:crypto.randomUUID(),amount:n,date:d}]}:y))}
 return <main className="min-h-screen bg-[#f4f5f7] text-slate-900 pb-16"><header className="bg-white border-b sticky top-0 z-20"><div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between"><div className="flex items-center gap-3"><img src="/brand/london-bite-logo.png" className="w-11 h-11 object-contain" alt="London Bite"/><div><h1 className="font-black leading-tight">London Bite Payables</h1><p className="text-xs text-slate-500">Supplier Khata Sheet</p></div></div><button onClick={()=>setAdd(!add)} className="bg-[#172554] text-white rounded-xl px-4 py-2.5 font-bold">+ Add Bill</button></div></header><section className="max-w-6xl mx-auto p-4">
 <div className="grid grid-cols-2 md:grid-cols-5 gap-2 mb-4"><Card l="Total Bills" v={money(total)}/><Card l="Paid" v={money(tp)}/><Card l="Dena Baqi" v={money(due)}/><Card l="Payable Bills" v={String(payable)}/><Card l="Cleared Bills" v={String(cleared)}/></div>
 {add&&<form onSubmit={save} className="bg-white border rounded-2xl p-4 mb-4"><h2 className="font-black text-lg mb-3">New Bill</h2><div className="grid md:grid-cols-5 gap-3"><Field label="Supplier Name"><input className="field" value={vendor} onChange={e=>setVendor(e.target.value)} required/></Field><Field label="Bill Amount"><input className="field" inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)} required/></Field><Field label="Paid Amount"><input className="field" inputMode="numeric" value={initialPaid} onChange={e=>setInitialPaid(e.target.value)}/></Field><Field label="Pending Amount"><input className="field bg-slate-50" value={money(Math.max(0,(Number(amount)||0)-(Number(initialPaid)||0)))} readOnly/></Field><Field label="Date"><input className="field" type="date" value={date} onChange={e=>setDate(e.target.value)} required/></Field></div><button className="mt-4 bg-[#172554] text-white rounded-xl px-6 py-3 font-bold">Save Bill</button></form>}
 <input className="field mb-3 max-w-sm" placeholder="Search supplier..." value={q} onChange={e=>setQ(e.target.value)}/>
 <div className="bg-white border rounded-2xl overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="bg-[#172554] text-white"><tr><Th>Supplier</Th><Th>Date</Th><Th>Bill Amount</Th><Th>Paid</Th><Th>Pending</Th><Th>Last Payment</Th><Th>Status</Th><Th>Action</Th></tr></thead><tbody>{rows.map(b=>{const p=paid(b),d=pending(b),last=b.payments.at(-1)?.date||"—";return <tr key={b.id} className="border-b last:border-0"><Td bold>{b.vendor}</Td><Td>{b.date}</Td><Td>{money(b.amount)}</Td><Td>{money(p)}</Td><Td bold>{money(d)}</Td><Td>{last}</Td><Td><span className={`px-2 py-1 rounded-full text-xs font-bold ${d===0?"bg-green-100 text-green-700":p>0?"bg-amber-100 text-amber-700":"bg-red-100 text-red-700"}`}>{d===0?"CLEARED":p>0?"PARTIAL":"PENDING"}</span></Td><Td>{d>0?<button onClick={()=>makePayment(b.id)} className="border border-[#172554] text-[#172554] rounded-lg px-3 py-2 font-bold">+ Payment</button>:"✓"}</Td></tr>})}{!rows.length&&<tr><td colSpan={8} className="text-center text-slate-400 py-12">No bills added yet.</td></tr>}</tbody></table></div>
 </section><style jsx global>{`.field{width:100%;border:1px solid #d1d5db;border-radius:10px;padding:11px 12px;background:white;outline:none}.field:focus{border-color:#172554}`}</style></main>}
function Card({l,v}:{l:string,v:string}){return <div className="bg-white border rounded-xl p-3"><div className="text-[11px] text-slate-500">{l}</div><div className="font-black text-lg">{v}</div></div>};function Field({label,children}:{label:string,children:React.ReactNode}){return <label><span className="block text-xs font-bold mb-1">{label}</span>{children}</label>};function Th({children}:{children:React.ReactNode}){return <th className="text-left px-4 py-3 whitespace-nowrap">{children}</th>};function Td({children,bold=false}:{children:React.ReactNode,bold?:boolean}){return <td className={`px-4 py-3 whitespace-nowrap ${bold?"font-bold":""}`}>{children}</td>}
