"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { LB_SUPABASE_URL, lbSignIn, readStoredLbSession, storeLbSession, type AuthSession } from "@/lib/lb-api";
import { setManagementBranchLocation } from "@/lib/lb-operations-api";
import { getLaunchReadiness, type LaunchReadiness, type ReadinessItem } from "@/lib/lb-readiness-api";

const panel = "rounded-[28px] border border-white/75 bg-white/72 p-5 shadow-[0_18px_55px_rgba(7,24,47,0.07)] backdrop-blur-2xl";
const field = "min-h-11 rounded-[14px] border border-lb-navy/10 bg-white/80 px-3 text-sm text-lb-ink outline-none focus:border-lb-blue/40 focus:ring-4 focus:ring-lb-blue/10";
const primary = "min-h-11 rounded-[14px] bg-lb-navy px-4 text-xs font-black text-white no-underline disabled:cursor-not-allowed disabled:opacity-40";
const secondary = "min-h-11 rounded-[14px] border border-lb-navy/10 bg-white/75 px-4 text-xs font-black text-lb-navy no-underline";
const definitions: { key: keyof LaunchReadiness; title: string; detail: string }[] = [
  { key: "menu", title: "Live menu", detail: "Production catalog contains active products." },
  { key: "order_pipeline", title: "Order pipeline", detail: "Customer → operations → kitchen/rider state model is live." },
  { key: "cash_orders", title: "Cash ordering", detail: "Customers can submit server-priced cash orders." },
  { key: "employees", title: "Real employee roster", detail: "Load the actual London Bite staff records." },
  { key: "staff_accounts", title: "Staff account linking", detail: "Link real staff identities to operational roles." },
  { key: "inventory", title: "Inventory baseline", detail: "Load current restaurant stock and thresholds." },
  { key: "geofence", title: "Branch geofence", detail: "Set verified restaurant coordinates from the premises." },
  { key: "online_payment", title: "Online payment gateway", detail: "Requires approved merchant credentials." },
  { key: "native_store_release", title: "App Store / Play Store release", detail: "Requires developer accounts, signing and store submission." },
];

function useSession() {
  const [session,setSessionState]=useState<AuthSession|null>(null);const[ready,setReady]=useState(false);
  useEffect(()=>{const hash=new URLSearchParams(window.location.hash.replace(/^#/,""));const access=hash.get("access_token");if(access){const next:AuthSession={access_token:access,refresh_token:hash.get("refresh_token")??undefined,expires_in:Number(hash.get("expires_in")??3600)};storeLbSession(next);setSessionState(next);window.history.replaceState({},"",window.location.pathname+window.location.search);}else setSessionState(readStoredLbSession());setReady(true);},[]);
  const setSession=(next:AuthSession|null)=>{storeLbSession(next);setSessionState(next);};return{session,setSession,ready};
}
function Login({onSignedIn}:{onSignedIn:(session:AuthSession)=>void}){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{onSignedIn(await lbSignIn(email,password));}catch(cause){setMessage(cause instanceof Error?cause.message:"Sign in failed");}finally{setBusy(false);}};const google=()=>{const redirect=`${window.location.origin}${window.location.pathname}${window.location.search}`;window.location.href=`${LB_SUPABASE_URL}/auth/v1/authorize?provider=google&redirect_to=${encodeURIComponent(redirect)}`;};return <section className={`mx-auto max-w-xl ${panel}`}><span className="text-[9px] font-black uppercase tracking-[0.16em] text-lb-blue">Protected management</span><h2 className="mb-2 mt-1 text-2xl font-black text-lb-navy">Management sign in</h2><form onSubmit={submit} className="mt-5 grid gap-3"><input required type="email" className={field} value={email} onChange={e=>setEmail(e.target.value)} placeholder="Work email"/><input required type="password" minLength={6} className={field} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/><button className={primary} disabled={busy}>{busy?"Checking…":"Sign in"}</button></form><button type="button" className={`${secondary} mt-2 w-full`} onClick={google}>Continue with Google</button><Link href="/staff/reset-password" className="mt-4 block text-center text-xs font-black text-lb-blue no-underline">Forgot password?</Link>{message&&<p className="mt-4 rounded-[14px] bg-red-50 p-3 text-xs font-bold text-red-700">{message}</p>}</section>;}
function Boundary({children}:{children:(token:string,signOut:()=>void)=>ReactNode}){const{session,setSession,ready}=useSession();if(!ready)return <section className={panel}>Loading secure session…</section>;if(!session?.access_token)return <Login onSignedIn={setSession}/>;return <>{children(session.access_token,()=>setSession(null))}</>;}
function Status({item}:{item:ReadinessItem}){if(item.ready)return <span className="rounded-full bg-green-50 px-2 py-1 text-[9px] font-black uppercase text-lb-green">Ready</span>;if(item.external)return <span className="rounded-full bg-blue-50 px-2 py-1 text-[9px] font-black uppercase text-lb-blue">External activation</span>;return <span className="rounded-full bg-amber-50 px-2 py-1 text-[9px] font-black uppercase text-amber-700">Needs setup</span>;}

export function LiveManagementSettingsReviewed(){return <Boundary>{(token,signOut)=><Settings token={token} signOut={signOut}/>}</Boundary>;}
function Settings({token,signOut}:{token:string;signOut:()=>void}){
  const[data,setData]=useState<LaunchReadiness|null>(null);const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setBusy(true);setMessage("");try{setData(await getLaunchReadiness(token));}catch(cause){setMessage(cause instanceof Error?cause.message:"Could not read readiness");}finally{setBusy(false);}},[token]);useEffect(()=>{void load();},[load]);
  const configure=()=>{if(!navigator.geolocation){setMessage("Geolocation is not supported on this device.");return;}setBusy(true);navigator.geolocation.getCurrentPosition(async(position)=>{try{await setManagementBranchLocation(token,position.coords.latitude,position.coords.longitude,100);setMessage(`SA Gardens geofence saved at ±${Math.round(position.coords.accuracy)}m device accuracy.`);await load();}catch(cause){setMessage(cause instanceof Error?cause.message:"Could not save location");}finally{setBusy(false);}},error=>{setMessage(error.message);setBusy(false);},{enableHighAccuracy:true,timeout:15000});};
  const progress=useMemo(()=>data?definitions.filter(({key})=>data[key].ready).length:0,[data]);
  return <div><div className="mb-3 flex justify-end gap-2"><button type="button" className={secondary} onClick={()=>void load()} disabled={busy}>Refresh readiness</button><button type="button" className={secondary} onClick={signOut}>Sign out</button></div>{message&&<p className="rounded-[14px] bg-lb-blue/5 p-3 text-xs font-bold text-lb-muted">{message}</p>}<div className="grid gap-3 xl:grid-cols-[0.75fr_1.25fr]"><section className={panel}><span className="text-[9px] font-black uppercase tracking-[0.16em] text-lb-blue">Attendance security</span><h2 className="mb-2 mt-1 text-2xl font-black text-lb-navy">Set the real restaurant geofence</h2><p className="text-sm leading-6 text-lb-muted">Run this only while physically inside London Bite. Employee check-in/out remains blocked until the real branch coordinates are verified.</p><button className={primary} onClick={configure} disabled={busy}>{busy?"Reading location…":"Use this device as branch location"}</button></section><section className={panel}><div className="flex items-start justify-between gap-3"><div><span className="text-[9px] font-black uppercase tracking-[0.16em] text-lb-blue">Go-live control</span><h2 className="mb-2 mt-1 text-2xl font-black text-lb-navy">Launch readiness</h2><p className="mb-0 max-w-2xl text-xs leading-5 text-lb-muted">Live database checks separate software readiness from real restaurant data and external accounts.</p></div>{data&&<strong className="rounded-full bg-lb-navy px-3 py-2 text-xs text-white">{progress}/{definitions.length}</strong>}</div>{data&&<div className="mt-4 grid gap-2 lg:grid-cols-2">{definitions.map(({key,title,detail})=>{const item=data[key];return <article key={key} className="flex items-start justify-between gap-3 rounded-[18px] border border-white/80 bg-white/60 p-3"><div><strong className="block text-xs text-lb-navy">{title}</strong><p className="mb-0 mt-1 text-[10px] leading-4 text-lb-muted">{detail}{typeof item.count==="number"?` Current count: ${item.count}.`:""}</p></div><Status item={item}/></article>;})}</div>}</section></div></div>;
}
