"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { submitCustomerFeedback } from "@/lib/lb-admin-extra-api";

const panel="rounded-[32px] border border-white/80 bg-white/75 p-6 shadow-[0_18px_60px_rgba(7,24,47,0.09)] backdrop-blur-2xl";
const field="min-h-12 rounded-[16px] border border-lb-navy/10 bg-white/85 px-4 text-sm text-lb-ink outline-none focus:border-lb-blue/40 focus:ring-4 focus:ring-lb-blue/10";
const primary="min-h-12 rounded-full bg-lb-navy px-6 text-sm font-black text-white disabled:opacity-40";

export default function FeedbackPage(){
  const[token,setToken]=useState("");const[rating,setRating]=useState(5);const[comment,setComment]=useState("");const[issue,setIssue]=useState("");const[message,setMessage]=useState("");const[busy,setBusy]=useState(false);
  useEffect(()=>{setToken(new URLSearchParams(window.location.search).get("token")??"");},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{await submitCustomerFeedback(token,rating,comment,issue);setMessage("Thanks — your feedback is attached to the delivered order.");}catch(cause){setMessage(cause instanceof Error?cause.message:"Feedback could not be saved.");}finally{setBusy(false);}};
  return <main className="min-h-screen bg-[#f4f5f2] px-4 py-8 text-lb-ink"><section className={`mx-auto max-w-2xl ${panel}`}><Link href="/order?view=history" className="text-xs font-black text-lb-blue no-underline">← Back to orders</Link><span className="mt-6 block text-[10px] font-black uppercase tracking-[0.16em] text-lb-red">Delivered-order feedback</span><h1 className="mb-2 mt-2 text-4xl font-black tracking-[-0.05em] text-lb-navy">How was your London Bite?</h1><p className="text-sm leading-6 text-lb-muted">Ratings can only be submitted against a valid tracking token for an order that management has marked delivered.</p><form onSubmit={submit} className="mt-6 grid gap-3"><label className="grid gap-1.5 text-xs font-black text-lb-navy">Tracking token<input required className={field} value={token} onChange={e=>setToken(e.target.value)} placeholder="Order tracking token"/></label><div><span className="text-xs font-black text-lb-navy">Rating</span><div className="mt-2 flex gap-2">{[1,2,3,4,5].map(value=><button key={value} type="button" onClick={()=>setRating(value)} className={`grid size-12 place-items-center rounded-full text-sm font-black ${rating===value?"bg-lb-navy text-white":"border border-lb-navy/10 bg-white/80 text-lb-navy"}`}>{value}</button>)}</div></div><label className="grid gap-1.5 text-xs font-black text-lb-navy">Issue category (optional)<select className={field} value={issue} onChange={e=>setIssue(e.target.value)}><option value="">No issue</option><option value="food_quality">Food quality</option><option value="wrong_order">Wrong order</option><option value="late_order">Late order</option><option value="delivery">Delivery</option><option value="service">Service</option><option value="other">Other</option></select></label><label className="grid gap-1.5 text-xs font-black text-lb-navy">Comment<textarea className={`${field} min-h-32 py-3`} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Tell London Bite what worked or what should improve."/></label><button className={primary} disabled={busy||!token}>{busy?"Saving…":"Submit feedback"}</button></form>{message&&<p className="mt-4 rounded-[16px] bg-lb-blue/5 p-3 text-xs leading-5 text-lb-muted">{message}</p>}</section></main>;
}
